apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rental-app-frontend
  name: rental-app-frontend
spec:
  selector:
    matchLabels:
      app: rental-app-frontend

  template:
    metadata:
      labels:
        app: rental-app-frontend
    spec:
      containers:
        - name: rental-app
          image: localhost:5010/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: rental-app-svc
  labels:
    app: rental-app-svc
spec:
  selector:
    app: rental-app-frontend
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rental-app-ingress
  labels:
    app: rental-app-ingress
spec:
  rules:
    - host:
      http:
        paths:
          - backend:
              service: 
                name: usr-svc-dev
                port:
                  number: 80
            pathType: Prefix
            path: /api/auth

          - backend:
             service:
                name: rental-app-svc
                port:
                  number: 80
            pathType: Prefix
            path: /

